# Generated by Django 4.2.25 on 2025-10-17 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='end_date',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='start_date',
            new_name='check_out',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='guest',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='room',
        ),
        migrations.AddField(
            model_name='reservation',
            name='hostel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostels.hostel'),
            preserve_default=False,
        ),
    ]
