# Generated by Django 4.2.25 on 2025-10-17 21:15

from django.db import migrations, models
import django.db.models.deletion
import hostels.models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_rename_end_date_reservation_check_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.AddField(
            model_name='hostel',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(default=hostels.models.get_default_room, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostels.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='number',
            field=models.CharField(default='A1', max_length=10),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostels.hostel'),
        ),
    ]
